### ISSUE TITLE
There is no test for getImage in pictogram_api.dart

### ISSUE THREAD

**Issue by TobiasPalludan** [aau-giraf/api_client#2]
Solve following todo.

```
Observable<Image> getImage(int id) {
    // TODO test this method
    return _http.get('/$id/image/raw').map((Response res) {
      return Image.memory(res.response.bodyBytes);
    });
  }
```

**Comment by joandrsn** [comment]
I'm starting to understand why this hasn't been done yet.

2 points:
The HTTP Mock library does not support binary files as the real `web-api` does.
This can be seen here: 
https://github.com/aau-giraf/api_client/blob/4eef9e8e4022f60680e182a64457183f5219d196/lib/http/http.dart#L13

Further more I'm questioning whether or not it is possible to test the function as it stands today.
Currently it utilises the [Image widget class](https://api.flutter.dev/flutter/widgets/Image-class.html). I cannot find any way of converting from a widget to the raw bytes (In order to test).
As such, I would suggest instead looking into returning an [ImageProvider](https://api.flutter.dev/flutter/painting/ImageProvider-class.html) which should be more suitable.
